int test2() {
  for (let i = 0; i < 5; i = i+1) {
    // i 在 for 循环作用域中
  }
  return i;  // 应该报错，因为 i 不在当前作用域
}
